version: '3.1'

services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8091:80"

  simple-sso-frontend:
    build: ../../frontend
    restart: always
    ports:
      - 8092:80

  simple-sso-backend:
    build: ../../backend
    restart: always
    ports:
      - 8093:8084
    environment:
      SPRING_DATA_MONGODB_HOST: mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
