
server:
  port: 8084

spring:
  application:
    name: simple-sso-proxy
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
  
secrets-cache-timeout: 60
persist-app-secrets: false
