spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true

httpclient:
  ssl:
    useInsecureContext: true

logging:
  level:
    dev:
      heinzl:
        simplessoproxy: DEBUG
